language: haskell
branches:
  only:
    - source

ghc:
  - 7.8

install:
  - sudo apt-get install rubygems && gem install sass
  - cabal install alex happy
  - cd generator
  - cabal install --force-reinstalls --only-dependencies --max-backjumps=-1
  - cabal configure && cabal build && cabal install
  - cd ..

before_script:
  - cd _site
  - git checkout master
  - git pull origin master
  - git checkout source .travis.yml
  - cd ..

script:
  - blog build

after_success:
  - cd _site
  - git status
  - git add --all
  - git config user.email "$GIT_NAME"
  - git config user.name "$GIT_EMAIL"
  - git commit -m "Deploy snapshot - $(date '+%m/%d/%y %H:%M')"
  - git push --force "https://${GH_TOKEN}@github.com/pxqr/pxqr.github.io.git" master &> /dev/null || echo push failed
  - cd ..
